---
  - debug:
      msg: "oah-install of oah.codeql"

    vars:
       clone_path_repo: '/home/vagrant/codeql-repo'
       clone_path_zip: '/opt/'

  - name: CodeQl binary fetch
    become: yes
    delegate_to: localhost
    get_url:
      url: https://github.com/github/codeql-cli-binaries/releases/download/v2.7.1/codeql-linux64.zip
      dest: "{{ clone_path_zip }}"
      timeout: 300

  - name: Extracting the codeql zip file
    shell: unzip "{{ clone_path_zip }}/codeql-linux64.zip"

  - name: Setting up symlinks
    become: yes
    shell: ln -s "{{ clone_path_zip }}"/codeql/codeql /usr/bin/cql

  - name: Download CodeQL sample queries for all supported languages.
    git:
      repo: https://github.com/be-secure/besip.git
      dest: "{{ clone_path_repo }}"
      clone: yes
      update: yes


