---
  - debug:
      msg: "oah-install of oah.codeql"

    vars:
            clone_path_repo: '/home/vagrant/test_role_codeql/codeql_repo'
            clone_path_zip: '/home/vagrant/test_role_codeql/codeql_repo/codeql_repos'

  - name: CodeQl Fetch
    become: yes
    delegate_to: localhost
    get_url:
      url: https://github.com/github/codeql-cli-binaries/releases/download/v2.7.1/codeql-linux64.zip
      dest: "{{ clone_path_zip }}"
      timeout: 300

  - name: Extracting the codeql zip file
    shell: unzip "{{ clone_path_zip }}"

  - name: Ensure codeql installed
    shell: sh codeql/codeql --version
    register: codeql_version

  - name: Download CodeQL sample queries for all supported languages.
    git:
      repo: https://github.com/github/codeql.git
      dest: "{{ clone_path_repo }}"
      clone: yes
      update: yes
